version: "3.8"

services:
  weather-api:
    build:
      context: ./weather
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./weather:/app
    env_file:
      - ./weather/.env
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  soil-api:
    build:
      context: ./soil
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8000"
    volumes:
      - ./soil:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
